adeVarGasamountInLiter = 3600;	
adeVarCylinderVolume = 12;
adeVarCylinderPressure = 300;
adeVarPercentO2 = 0.12;
adeVarPercentN2 = 0.23;
adeVarPercentHe = 0.65;
adeVarDiverWithoutGas = 0;
player removeItem "ade_item_cylinder_linked_6ltr_300bar_Tx1265";
playSound "ade_sound_zischen";
hint "Filled rebreather using linkede 6l cylinders, filled with 300bar of Tx 12/65.";
player addItem "ade_item_cylinder_linked_6ltr_empty";