adeVarGasamountInLiter = 1800;	
adeVarCylinderVolume = 6;
adeVarCylinderPressure = 300;
adeVarPercentO2 = 0.085;
adeVarPercentN2 = 0;
adeVarPercentHe = 0.915;
adeVarDiverWithoutGas = 0;
player removeItem "ade_item_cylinder_single_6ltr_300bar_Heliox85";
playSound "ade_sound_zischen";
hint "Filled rebreather using single 6l cylinder, filled with 300bar of Heliox 8.5.";
player addItem "ade_item_cylinder_single_6ltr_empty";