adeVarGasamountInLiter = 3600;	
adeVarCylinderVolume = 12;
adeVarCylinderPressure = 300;
adeVarPercentO2 = 0.28;
adeVarPercentN2 = 0.72;
adeVarPercentHe = 0;
adeVarDiverWithoutGas = 0;
player removeItem "ade_item_cylinder_linked_6ltr_300bar_EAN28";
playSound "ade_sound_zischen";
hint "Filled rebreather using linked 6l cylinders, filled with 300bar of EAN 28.";
player addItem "ade_item_cylinder_linked_single_6ltr_empty";