adeVarGasamountInLiter = 1800;	
adeVarCylinderVolume = 6;
adeVarCylinderPressure = 300;
adeVarPercentO2 = 0.21;
adeVarPercentN2 = 0.78;
adeVarPercentHe = 0.01;
adeVarDiverWithoutGas = 0;
player removeItem "ade_item_cylinder_single_6ltr_300bar_compressedAir";
playSound "ade_sound_zischen";
hint "Filled rebreather using single 6l cylinder, filled with 300bar of compressed air.";
player addItem "ade_item_cylinder_single_6ltr_empty";