adeVarGasamountInLiter = 3600;	
adeVarCylinderVolume = 12;
adeVarCylinderPressure = 300;
adeVarPercentO2 = 0.40;
adeVarPercentN2 = 0.60;
adeVarPercentHe = 0;
adeVarDiverWithoutGas = 0;
player removeItem "ade_item_cylinder_linked_6ltr_300bar_EAN40";
playSound "ade_sound_zischen";
hint "Filled rebreather using linked 6l cylinders, filled with 300bar of EAN 40.";
player addItem "ade_item_cylinder_linked_6ltr_empty";